const BAD_REQUEST_CODE = 400;
const NOT_FOUND_CODE = 404;
const SERVER_ERROR_CODE = 500;
const UNAUTHORIZED = 401;
const FORBIDDEN = 401;

module.exports = {
  BAD_REQUEST_CODE,
  NOT_FOUND_CODE,
  SERVER_ERROR_CODE,
  UNAUTHORIZED,
  FORBIDDEN,
};
